### ISSUE TITLE
Move away from HAML

### ISSUE THREAD

**Issue by hpoom** [colynb/generator-go-static#5]
I am liking Go-Static so far as it is less bloated then the 'webapp' yo generator. The only issue for me is it uses HAML.

I am personally looking for a 100% Javascript solution and HAML is not very JS in my view. So for now I have changed to using [Punch](http://laktek.github.io/punch/) which dies not have a Yo generator yet, but does use handlebars for templating.

Maybe we could move Go-Static to handlebars? or maybe look at some of the best bits of all the javascipt static site generators out there and merge them into one great Yo generator for static sites that is 100% JS.

**Comment by colynb** [comment]
Good to hear that people are using go-static and find it useful, so I really appreciate the feedback. There's definitely a lot of work that needs to happen before I would consider this polished, but I think you misunderstand my reasoning for using HAML. I'm not actually a fan of HAML but I used it as an example of how to use an HTML preprocessor other than markdown. HAML is not a template language. The template language I use for go-static is called [Swig](http://paularmstrong.github.io/swig/) which IS a 100% javascript template language very similar to handlebars. In my day job, I use swig on almost every project after trying a couple different ones, such as EJS. It's very similar to django templates or php Twig. The way it allows to to create blocks and inherit from layouts is a really great feature.

**Comment by hpoom** [comment]
Thanks for the update. What is HAML giving you now as a preprocessor that you could not achieve with a templating language?

Maybe I have missed some code, but the only HAML I have seen so far is loops, conditions, and output of vars in the go-static files. All of which could be achieved with handlebars. I have never heard of Swig, but I will check it out. Where can I see examples of Swig in go-static, so far I have only seen HAML and not seen any templating.

I am not really a far of  django templates or php twig. In both python and PHP I use mustache.

Regarding you mention of it not being polished, what is the direction you want to take? How will it differ from say something like Punch? Also need any help?

**Comment by colynb** [comment]
I'm pretty sure HAML is just a preprocessor which doesn't include things like loops and conditionals and other things that template languages give you. Here's an example of some HAML that I use in one of my templates:

```
%h1.content-subhead
  Pinned Post
```

 which simply outputs

```
<h1 class="content-subhead">Pinned Post</h1>
```

All the other code you see such as 

```
{% for post in pinnedposts %}
```

comes from swig.

Swig comes with what I think is its defining feature, and that is the ability to inherit other templates for creating layouts. It's very nice. (see http://paularmstrong.github.io/swig/docs/#inheritance)

Right now, in go-static when you create a template, you define your layout in the YAML section at the top. One thing that I've been meaning to get to is remove that requirement since layout inheritance is a native function, meaning you can just define your layout in the same way as the example in the link. As it is, I've had to write a bunch of code in order to manage layouts through the YAML section. Removing that part will clean up the code even more.

**Comment by colynb** [comment]
The direction I want to take is not to build something as a stand alone static site generator, like Docpad or Jeckyll are. I haven't heard of Punch before (but looking at the site, it makes me thirsty lol) and it looks like it's also a stand alone app. I just want something that isn't magical, is transparent and easy to understand. I think building your site out with existing tools like Yeoman and Grunt helps with that goal. Not as ambitious as the others, but I think that's a good thing. I've been using go-static in my day job and for side projects for quickly building out prototype websites, and mockups, and I think that's probably where it works best.

**Comment by hpoom** [comment]
It's OK I was being dumb as was tiered and late at night. I mistook the swig for HAML.

I agree with you on using existing tools like Yeoman and Grunt, that is how I stumbled on Go-Static. I might  try and turn Punch into a Yo Generator. It does sound like Go-Static and punch have similar goals, but I understand they will probably remain separate. I this morning created the same site in both and for now I quite like Punch, but I do with it would use Yeoman and Grunt and not a custom CLI tool.

Going to read more about Swig, thanks for introducing that to me.
